### ISSUE TITLE
Not an issue but a question.

### ISSUE THREAD

**Issue by AdamKearn** [ayufan-rock64/chromium-overlay-rockpro64#1]
Hey, nice work dude.

Just wondering, when you build your images are you passing the `dev` flag to the `./build_image` command??
if so then you should never login to them.  They are insecure and could compromise your Google account.

I am asking this because I looked at your `scripts/release.sh` file.  `LN 16`
[https://github.com/ayufan-rock64/chromiumos-build/blob/da13f68e7942a4f5beff0743ec456f288fd53c3c/scripts/release.sh#L12-L16](https://github.com/ayufan-rock64/chromiumos-build/blob/da13f68e7942a4f5beff0743ec456f288fd53c3c/scripts/release.sh#L12-L16)

You should be building images with the base command or with no flag. 
e.g.
```
./build_image --board=${BOARD} base
or
./build_image --board=${BOARD}
```

**Comment by ayufan** [comment]
You know that:

```bash
./build_image --board=${BOARD}
# is equal to
./build_image --board=${BOARD} dev
```

BTW. I build `base` and `dev` variant. It is not that `dev` is insecure! It is `dev` has more packages installed that increase attack surface, like `ssh` deamon that needs to be secured, etc. It is also not true that `base` is secure, it is not current builds as there's no `rootfs verification` etc. and number of other things that should be configured.

**Comment by AdamKearn** [comment]
Ok, thanks for pointing that out to me.
